### PR TITLE
Make gamescope's "Switch To Desktop" quit steam

### PR DESCRIPTION
**Pull request by shocklateboy92**
The "Exit Steam" button disappears when running in gamescope, so this is the only way I can think of to quit properly.

### CODE REVIEW

**Comment by ABeltramo** [comment]
Makes sense, shall we wrap that execution in a conditional based on the env variable `RUN_GAMESCOPE`?  
I'd like to keep the ability to switch to the normal switch to desktop functionality when running on Sway

**Comment by shocklateboy92** [comment]
So, steam doesn't have a "Switch To Desktop" button when running in sway:
image

presumably because it knows it's already running in a "desktop" and just has "Exit Steam" instead, which AFAICT does not invoke that script.

**Comment by ABeltramo** [comment]
It should be the "Exit big picture mode" button, no?  
I'll give it a go on my setup, I can't remember what is the menu on Gamescope from the top of my head..

**Comment by shocklateboy92** [comment]
I just tested it. "Exit big picture mode" does not run this script. I just kills the steam tenfoot window and opens the main window.

When running in gamescope, steam thinks it's running on the steam deck which has no window manager or session underneath, so it launches this script (or the version of it on steamos) that _creates_ a new desktop session and puts the user into it.

**Comment by ABeltramo** [comment]
I've tested quickly, and it seems that it doesn't get triggered when running in Sway.   

I guess we could probably run Sway and switch Steam to the desktop mode similar to how they do it in the Steam Deck by running KDE, but this looks good enough for now. Thanks!

**Pull request merged**
