### PR TITLE
Ansible to install and run GOW in headless mode

### PR DESCRIPTION
**Pull request by Kimi450**
Ansible to install and run GOW in headless mode

Items covered:
- Pre-reqs about `/dev/uinput` being present
- Monitor requirements from section 3 in https://games-on-whales.github.io/gow/monitor.html
  - 3.3 is missing at the moment, dont know how to do this cleanly
- cloning of repo
- configs
  - local_state
  - time_zone

### CODE REVIEW

**Comment by Kimi450** [comment]
Section 3.3 in [here](https://games-on-whales.github.io/gow/monitor.html), I dunno if theres a way to parse the yaml to add the specific lines from the docs in it. I dont wanna just do a blockinfile for a lineafter, that doesnt seem very robust. 

After that, the pre-req stuff should be done. Running pull and up for at least firefox will work after that, but we need the pin to connect from Moonlight. For that, we need to access the UI through the server. To allow for external access, `origin_pin_allowed` needs to be set to `wan` in `sunshine.conf` file. The only way to currently give this file to the docker container is by probably building the image ourselves. 

So these 2 should be the next items we look at I think @ABeltramo

**Comment by Kimi450** [comment]
Need to add a readme for this

**Comment by Kimi450** [comment]
> Need to add a readme for this

done

**Comment by shocklateboy92** [comment]
Hey @Kimi450, thanks for all your hard work on this contribution!

Unfortunately, GOW itself is no longer maintained and we recommend people switch to [Wolf](https://github.com/games-on-whales/wolf) instead. As such, I'm going ahead and closing all the (now stale) PRs that target GOW.

Wolf still uses the docker images that were built for GOW, so we're going to switch this repo to contain images only.

**Pull request closed without merging**
