### PR TITLE
Adding working Lutris based on steam

### PR DESCRIPTION
**Pull request by Murazaki**
Here you are, pretty basic version though but works.

### CODE REVIEW

**Comment by Murazaki** [comment]
As a note :

I can run a bunch of games from Steam or Epic Games Store on an old AMD Cedar Radeon :
- A Short Hike
- Final Fantasy III 3D Remake

Anything more modern crashes but I can't tell if it's a DirectX/Vulkan issue or a HW issue.
Vulkan is looking for wrong drivers sometimes. For instance while trying to run The Vanishing of Ethan Carter :

```
2023-01-08 17:45:02,650: Unable to load libGLX_nvidia.so.0
2023-01-08 17:45:02,650: Unable to locate libGLX_nvidia
Discord ID: None
2023-01-08 17:45:02,849: Discord RPC Disabled or Discord APP ID Not Present
Started initial process 7630 from /home/retro/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/retro/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/9447b19ffb6a47e1a654b75178779a28?action=launch
Start monitoring process.
wine client error:0: version mismatch 759/748.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2023-01-08 17:45:04,854: Game still running (state: running)
2023-01-08 17:45:04,854: Stopping The Vanishing of Ethan Carter (wine)
2023-01-08 17:45:04,855: The game has run for a very short time, did it crash?
```
(Lutris is also forcing a different version of wine)

Here are people with the same issue with Lutris on desktop
https://forum.manjaro.org/t/vulkan-not-supported-on-lutris/90563

**Comment by Murazaki** [comment]
Just made Life Is Strange run on Low graphics mode, so it might just be a directx11 + modern shader issue

**Comment by Murazaki** [comment]
Rebased to master.

**Comment by ABeltramo** [comment]
Superseeded by https://github.com/games-on-whales/gow/pull/177

**Pull request closed without merging**
