### PR TITLE
Draft: Add EmulationStation-DE image (based on RetroArch) and several emulators to use with it

### PR DESCRIPTION
**Pull request by QuaiGoner**
**Software added in the image:**
- **EmulationStation-DE** ref: https://gitlab.com/es-de/emulationstation-de, all credits for app goes there

**Emulators added in the image:**
- **Retroarch** (based on it)
- **pcsx2** via Appimage
- **XEMU** via Appimage
- **RPCS3** via Appimage
- **YUZU** via Appimage
- ~~**Wine** via PPA (with winetricks)~~
- ~~**Steam**~~

**Other additions in the image:**
- Custom configs for Wolf gamepads for various emulators
- Single BIOS directory for all emulators in /bioses
- ES media in /Media
- ROMs in /ROMs
- Custom platform in EmulationStation with various launch scripts

RetroArch-image based
From my initial testing all seems to be working, but need broader testing
I think this project (ESDE) can be a great base for a broader emulation/retro-gaming image for GOW
ROMs paths follow RetroPie/other ES based project (psx,ps2,ps3,wii, etc...)
kinda supercedes https://github.com/games-on-whales/gow/pull/139

**BIOS/Keys:**
 - Mount your ROMs folder to /ROMs
 - Mount your BIOSes folder to /bioses with following:
    - RetroArch bioses
    - Xemu BIOS and hdd image
    - PCSX2 BIOS
    - Yuzu keys
    - RPCS3 FW

**What to do after first startup:**
 - Launch RPCS3 Firmware install script from Custom Scripts (!Install_RPCS3_Firmware) and proceed with installation, close RPCS3
 - Launch RetroArch from Custom Scripts and install cores for your use (**NO CORES SHIPPED WITH THE IMAGE**)

TODO:
- [x] Make everything work
   - [x] Launch&Play PCSX2 (qt packages were needed)
   - [x] Launch&Play XEMU (crashes on startup - `ALSA related`) - was not image related
   - [x] Launch&Play RPCS3 (qt packages and additional vulkan were needed)
   - [x] Launch&Play YUZU (crashes after loading game - YUZU Requires a lot of RAM, 16 GB at least)
   - [x] Fix RPCS3 Sound - was not image related
   - [x] Fix PCSX2 Sound - was not image related
- [x] Make everything more user-friendly and automatic
   - [x] RPCS3 Firmware install (added custom script for installing since there is no way install it without user interaction)
   - [x] Disable RPCS3 auto-update pop-up and succesfull FW install pop-up
   - [x] Disable YUZU telemetry pop-up in startup script
   - [x] single BIOS/keys location/FW
   - [x] Bind PCSX2 pause menu button in startup script
   - [x] Bind Wolf Gamepads for PCSX2 in startup script
   - [x] Bind Wolf Gamepads for RPCS3 in startup script
   - [x] Rename сustom platform to "Scripts", add Icon
- [ ] Maintance
   - [x] Shrink the image. Image is about 3.6 gigs (Already doing cleanup on every stage)
   - [x] Hard-code resource allocation in config.toml (70% for CPU) - it is very easy with emulation to load your system to 100 percent (see config.toml example)
   - [x] Wait for Wolf release (with base-app image) for migrating to that
   - [x] Migrate to ENVs and relative links in pre-defined configs (for multiple users configurations - not only retro)
      - [x] Move ROMs directory from retro user
      - [x] Move Bioses directory from retro user
      - [x] Move Downloaded Media directory from retro user
      - [x] Move AppImages directory from retro user (for multiple users configurations - not only retro)
      - [x] Verify that saves folders are relative to $HOME 
      - [x] Move XEMU hdd location to saves, for consistency and dropping write access for bioses
   - [x] Test First-time startup and write up steps to have fully ready install
   - [ ] Fix RPCS3 wrong gamepad allocation (using EVDEV and single controller is binding to number 4)
- [ ] Optional
   - [x] ~~Add Steam with launch script~~
   - [x] ~~Add Wine~~
   - [x] ~~Add DXVK~~
   - [ ] Add more emulators (Dolphin, Xenia via Wine?, CEMU via Wine?)
   - [x] single saves location for emulators per user (now everything is basically in $HOME, so for multi-user usage we just can switch $HOME variable for every new user connected to Wolf)
   - [ ] testing
      - [ ] Clean First Startup
      - [x] Other cases
   - [ ] Documentation (if PR got merged)
      - [ ] First Startup
      - [ ] Troubleshooting
      - [ ] Examples

### CODE REVIEW

**Comment by QuaiGoner** [comment]
AppImages dont work for some reason, need to investigate

**Comment by QuaiGoner** [comment]
Appimages seems to be fixed with additional fuse images:
- fuse \
- libfuse2 \

**Comment by QuaiGoner** [comment]
The one issue with that image that i see:
- ROMs default location is inside of the home "retro" folder which we already mapping for persistance, but it seems to be working okay with several mountpoint (to /home/retro/ROMs and /home/retro)

Marking it as ready to review

**Comment by QuaiGoner** [comment]
Marking as Draft until Wolf is released, and will rebase

**Comment by QuaiGoner** [comment]
Appimages fixed thanks to drakulix help on discord.
Latest TODO:
Fix and test Wine
Deal with some random audio-related crashes in YUZU (RPCS3 also throws error but dont crash)
Deal with some random vulkan-related crashes (might be related to Wolf)

**Comment by QuaiGoner** [comment]
RPCS3 needs larger limits
https://github.com/RPCS3/rpcs3/issues/9328

**Comment by solipsist01** [comment]
i have tested the emulationstationde commits, and so far it looks really promising.
there's one thing. emulationstationde doesn't seem to support an 'exit key' on a gamepad. This is from their FAQ


**How do I exit back from the emulators to ES-DE?**
This is related to the two questions above, ES-DE does not perform any emulator configuration or general system configuration. So you would either need to configure an exit button combination inside your emulator, or use a third party tool to map for instance Alt + F4 or Command + Q to a certain button combination on your controller. If you use RetroArch then it's easy to setup a button combination to exit back to ES-DE, which will apply to all cores. Refer to the RetroArch documentation or their support channels on how to accomplish this.


I think we need to figure out a workaround for that, as we can't alt+f4 through moonlight.
when i have free time, i was thinking of making some background python script which listens to certain gamepad combo's, and then presses alt + f4. perhaps there's a better way.

**Comment by QuaiGoner** [comment]
> i have tested the emulationstationde commits, and so far it looks really promising. there's one thing. emulationstationde doesn't seem to support an 'exit key' on a gamepad. This is from their FAQ
> 
> **How do I exit back from the emulators to ES-DE?** This is related to the two questions above, ES-DE does not perform any emulator configuration or general system configuration. So you would either need to configure an exit button combination inside your emulator, or use a third party tool to map for instance Alt + F4 or Command + Q to a certain button combination on your controller. If you use RetroArch then it's easy to setup a button combination to exit back to ES-DE, which will apply to all cores. Refer to the RetroArch documentation or their support channels on how to accomplish this.
> 
> I think we need to figure out a workaround for that, as we can't alt+f4 through moonlight. when i have free time, i was thinking of making some background python script which listens to certain gamepad combo's, and then presses alt + f4. or, we link docker.sock, and restart the gow-emulationstation-1 container when a gamepad combo is pressed.

Thanks for testing.
There is several configs for emulators predefined for the ability to exit game back to ES-DE. (Try pressing Home for PCSX2 and RPCS3, or Start+Select for RetroArch, or Home + Select for YUZU)
But if we want to kill a moonlight session from the app, i think it would require fiddle with Wolf sources

**Comment by solipsist01** [comment]
The bindings work perfectly. Perhaps all rebind to one universal setup. Like batocera. I had to do some alterations to the dockerfile to get the image working. Like the socket dir didnt exist. And, esde starts before the x server is ready, so the resolution gets messed up. Do you want pull requests?

**Comment by QuaiGoner** [comment]
> Like the socket dir didnt exist. And, esde starts before the x server is ready

weird, i havent had that issue. Can ypu submit a PR for the changes on my repo?
I am gonna try and reproduce the problem

**Comment by QuaiGoner** [comment]
Recent wolf-changes branch broke building of ES-DE image. Reverting to latest working

**Comment by QuaiGoner** [comment]
@ABeltramo i see that you implemented per-session user storage. Does it work well with $HOME ENV?
My image should work fine, if we announce proper $HOME per session

**Pull request merged**
